---
- name: Install and start Nginx web server
  hosts: webservers
  become: yes

  tasks:
    - name: Update apt cache (for Debian/Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install nginx
      apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure nginx service is running and enabled
      service:
        name: nginx
        state: started
        enabled: yes
